
networks:
  # Exposed to the public -- in use by nginx
  frontend_network:
    driver: bridge
  # Internal backend network for ODNS-API and nginx
  # nginx serves as entrypoint to the ODNS-API 
  odnsapi_network:
    driver: bridge
    internal: true 
  # Network used to isolate database from the public, nginx cannot connect to it
  # This network is only used to connect the ODNS-API, and pgadmin with Postgres DB
  postgresdb_network:
    driver: bridge
    internal: true 
  # Network for pgadmin -- only exposed to localhost
  local_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  # Network for observability
  observability:
    driver: bridge
    internal: true 

volumes:
  # Mount shared drive for data importer
  odns_data:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${SAMBA_USER},password=${SAMBA_PASSWORD},vers=3.0"
      device: "//${SAMBA_SHARE}"
  # Volume for postgres db
  postgres_data:
  data_importer_tmp:
  # InfluxDB
  influxdb-data:
