log_format odns_json escape=json '{'
    '"time":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"method":"$request_method",'
    '"host":"$host",'
    '"uri":"$uri",'
    '"request_uri":"$request_uri",'
    '"status":"$status",'
    '"status_code":$status,'
    '"body_bytes_sent":$body_bytes_sent,'
    '"request_length":$request_length,'
    '"request_time":$request_time,'
    '"upstream_addr":"$upstream_addr",'
    '"upstream_status":"$upstream_status",'
    '"upstream_response_time":"$upstream_response_time",'
    '"http_referer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
'}';

access_log /var/log/nginx/access.log odns_json;
error_log /var/log/nginx/error.log warn;

server {
    listen 80;
    server_name odns-data.netd.cs.tu-dresden.de;

    # Redirect everything else to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name odns-data.netd.cs.tu-dresden.de;

    ssl_certificate /etc/letsencrypt/live/odns-data.netd.cs.tu-dresden.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/odns-data.netd.cs.tu-dresden.de/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    location /docs {
        proxy_pass http://dotnet_app:5551;
            proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /swagger {
        proxy_pass http://dotnet_app:5551;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api {
        proxy_pass http://dotnet_app:5551;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 1800;
        proxy_connect_timeout 1800;
        proxy_send_timeout 1800;
        send_timeout 1800;
    }
    location /_downloads/ {
        internal;
        alias /data/downloads/;
        types {
            text/csv csv;
            application/zstd zst;
            application/vnd.apache.parquet parquet;
        }
        default_type application/octet-stream;
        add_header X-Content-Type-Options nosniff always;
    }

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

}
